# With GitHub Pages Gem
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: MyFantasyLeague.com (MFL) Repository
description: Working on building a way for me to access css, images, svgs and other files saved here from my fantasy football league websites.
