remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: MyFantasyLeague (MFL) Assets
description: A simple website for easy access to CSS, images, and other documents for my league websites.
